backend:
  name: git-gateway
  branch: master
media_folder: public/assets/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/pages/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Hero Title", name: "hero_title", widget: "string" }
        - { label: "Hero Description", name: "hero_description", widget: "text" }
        - { label: "Body", name: "body", widget: "markdown"}
        - { label: 'Cats', 
            name: "cats", 
            widget: list, 
            fields: [
              { label: "Name", name: "name", widget: "string"},
              { label: "Description", name: "description", widget: "text"}  
            ]
          }